## 建構神經網路

In [2]:
import numpy as np
x = np.array([-1,1,2])
x

array([-1,  1,  2])

In [3]:
x > 0 

array([False,  True,  True])

In [4]:
(x > 0).astype(int)

array([0, 1, 1])

In [5]:
def threshold_function(x):
    y = x > 0
    return y.astype(int)

x = np.array([-1,1,2])

threshold_function(x)


array([0, 1, 1])

In [7]:
def sigmoid_function(x):
    return 1/ (1 + np.exp(-x))
x = np.array([-1,1,2])
sigmoid_function(x)

array([0.26894142, 0.73105858, 0.88079708])

In [8]:
x = np.array([-100,1,200])
sigmoid_function(x)

array([3.72007598e-44, 7.31058579e-01, 1.00000000e+00])

In [9]:
def tangent_function(x):
    return (1 - np.exp(-2*x)) / (1 + np.exp(-2*x))

x = np.array([-1,1,2])
tangent_function(x)


array([-0.76159416,  0.76159416,  0.96402758])

In [10]:
np.tanh(x)

array([-0.76159416,  0.76159416,  0.96402758])

In [11]:
def relu_function(x):
    return np.maximum(0,x)

x = np.array([-1,1,2])
relu_function(x)


array([0, 1, 2])

In [12]:
import numpy as np
X = np.array( [1,2])

W = np.array([[1,3,5],\
              [2,4,6]])

Y = np.dot(X,W)
Y


array([ 5, 11, 17])

In [13]:
network = {}
network['w1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
network['b1'] = np.array([0.1,0.2,0.3])
network['w2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
network['b2'] = np.array([0.1,0.2])


In [14]:
x = np.array([1,0.5])
a = np.dot(x, network['w1']) + network['b1']
a

array([0.3, 0.7, 1.1])

In [15]:
z = sigmoid_function(a)
z

array([0.57444252, 0.66818777, 0.75026011])

In [17]:
y = np.dot(z, network['w2']) + network['b2']
y

array([0.51615984, 1.21402696])

In [18]:
def softmax_function(x):
    return np.exp(x) / np.sum(np.exp(x))

softmax_function(y)

array([0.33228528, 0.66771472])