In [3]:
from sklearn.feature_extraction.text import CountVectorizer
#?CountVectorizer
vectorizer = CountVectorizer(min_df=1)
content = ["How to format my hard disk", " Hard disk format problems "]
X = vectorizer.fit_transform(content)

In [4]:
print(vectorizer.get_feature_names())

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']


In [5]:
print(X.toarray())

[[1 1 1 1 1 0 1]
 [1 1 1 0 0 1 0]]


In [8]:
import os
path = 'data/toy/'
posts = []
for fname in os.listdir(path):
    posts.append(open(path + fname).read())

In [9]:
posts

['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [16]:
posts = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=1)

In [11]:
X_train = vectorizer.fit_transform(posts)
num_samples, num_features = X_train.shape


In [12]:
X_train.shape

(5, 25)

In [15]:
print(vectorizer.get_feature_names())

['about', 'actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'this', 'toy']


In [13]:
X_train.toarray()

array([[1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0],
       [0, 0, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 0]], dtype=int64)

In [20]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])


In [21]:
new_post_vec.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [40]:
type(new_post_vec.toarray())

numpy.ndarray

In [22]:
import scipy as sp

# euclidean
# sqrt(sum((v1 - v2) ** 2))

def dist_raw(v1, v2):
    delta = v1 - v2
    return sp.linalg.norm(delta.toarray())


In [30]:
import numpy as np
import math
a  = np.array([0,0,1,1,0])
b  = np.array([1,0,1,1,1])
np.sqrt(sum((a - b) ** 2))

1.4142135623730951

In [32]:
sp.linalg.norm( (a - b))

1.4142135623730951

In [45]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist_raw(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 3.872983346207417
Imaging databases provide storage capabilities. 2.0
Most imaging databases safe images permanently. 2.23606797749979
Imaging databases store data. 1.7320508075688772
Imaging databases store data. Imaging databases store data. Imaging databases store data. 5.5677643628300215


In [55]:
def dist(v1, v2):
    v1_normalized  = v1 / sp.linalg.norm(v1.toarray()) 
    v2_normalized  = v2 / sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())


In [46]:
# 小內閣之一是她？ 「王淺秋」內定高市新聞局長
# 韓國瑜要在一個月內完成小內閣組閣，局處首長人選，他說目前找到了一半，至於名單有誰，韓國瑜說直接講名字很敏感，會在就職日公布，不過前一天，韓國瑜北上參加私人餐會，媒體在現場等待時間，六福集團的公關協理王淺秋儼然像公關，在場當協調橋樑，加上王淺秋過去就有新聞媒體背景，外傳將接任高雄市新聞局長。

In [47]:
# 小內閣 王淺秋 高市 新聞局長
# 小內閣 王淺秋 高市 新聞局長 韓國瑜 首長 人選 一半 名單 敏感...

In [51]:
a = np.array([1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
b = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
delta = a - b
sp.linalg.norm(delta)

4.0

In [53]:
a = np.array([1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
b = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
a_normalized  = a / sp.linalg.norm(a) 
b_normalized  = b / sp.linalg.norm(b)
delta = a_normalized - b_normalized
sp.linalg.norm(delta)

1.0514622242382672

In [56]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.4142135623730951
Imaging databases provide storage capabilities. 1.0514622242382672
Most imaging databases safe images permanently. 1.0878894332937856
Imaging databases store data. 1.0
Imaging databases store data. Imaging databases store data. Imaging databases store data. 1.0
