## 英文詞頻矩陣

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
#?CountVectorizer
vectorizer = CountVectorizer(min_df=1)
content = ["How to format my hard disk", " Hard disk format problems "]
X = vectorizer.fit_transform(content)

In [4]:
print(vectorizer.get_feature_names())

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']


In [5]:
print(X.toarray())

[[1 1 1 1 1 0 1]
 [1 1 1 0 0 1 0]]


In [8]:
import os
path = 'data/toy/'
posts = []
for fname in os.listdir(path):
    posts.append(open(path + fname).read())

In [9]:
posts

['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [16]:
posts = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=1)

In [11]:
X_train = vectorizer.fit_transform(posts)
num_samples, num_features = X_train.shape


In [12]:
X_train.shape

(5, 25)

In [15]:
print(vectorizer.get_feature_names())

['about', 'actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'this', 'toy']


In [13]:
X_train.toarray()

array([[1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0],
       [0, 0, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 0]], dtype=int64)

In [20]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])


In [21]:
new_post_vec.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [40]:
type(new_post_vec.toarray())

numpy.ndarray

In [22]:
import scipy as sp

# euclidean
# sqrt(sum((v1 - v2) ** 2))

def dist_raw(v1, v2):
    delta = v1 - v2
    return sp.linalg.norm(delta.toarray())


In [30]:
import numpy as np
import math
a  = np.array([0,0,1,1,0])
b  = np.array([1,0,1,1,1])
np.sqrt(sum((a - b) ** 2))

1.4142135623730951

In [32]:
sp.linalg.norm( (a - b))

1.4142135623730951

In [45]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist_raw(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 3.872983346207417
Imaging databases provide storage capabilities. 2.0
Most imaging databases safe images permanently. 2.23606797749979
Imaging databases store data. 1.7320508075688772
Imaging databases store data. Imaging databases store data. Imaging databases store data. 5.5677643628300215


In [55]:
def dist(v1, v2):
    v1_normalized  = v1 / sp.linalg.norm(v1.toarray()) 
    v2_normalized  = v2 / sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())


In [46]:
# 小內閣之一是她？ 「王淺秋」內定高市新聞局長
# 韓國瑜要在一個月內完成小內閣組閣，局處首長人選，他說目前找到了一半，至於名單有誰，韓國瑜說直接講名字很敏感，會在就職日公布，不過前一天，韓國瑜北上參加私人餐會，媒體在現場等待時間，六福集團的公關協理王淺秋儼然像公關，在場當協調橋樑，加上王淺秋過去就有新聞媒體背景，外傳將接任高雄市新聞局長。

In [47]:
# 小內閣 王淺秋 高市 新聞局長
# 小內閣 王淺秋 高市 新聞局長 韓國瑜 首長 人選 一半 名單 敏感...

In [51]:
a = np.array([1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
b = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
delta = a - b
sp.linalg.norm(delta)

4.0

In [53]:
a = np.array([1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
b = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
a_normalized  = a / sp.linalg.norm(a) 
b_normalized  = b / sp.linalg.norm(b)
delta = a_normalized - b_normalized
sp.linalg.norm(delta)

1.0514622242382672

In [56]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.4142135623730951
Imaging databases provide storage capabilities. 1.0514622242382672
Most imaging databases safe images permanently. 1.0878894332937856
Imaging databases store data. 1.0
Imaging databases store data. Imaging databases store data. Imaging databases store data. 1.0


In [62]:
vectorizer = CountVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())


['actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'learning', 'machine', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'toy']


In [59]:
len(vectorizer.get_feature_names())

18

In [60]:
list(vectorizer.get_stop_words())[0:10]

['noone',
 'our',
 'next',
 'her',
 'other',
 'formerly',
 'around',
 'fifteen',
 'rather',
 'nevertheless']

In [63]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])


In [64]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.4142135623730951
Imaging databases provide storage capabilities. 1.0514622242382672
Most imaging databases safe images permanently. 1.0514622242382672
Imaging databases store data. 1.0
Imaging databases store data. Imaging databases store data. Imaging databases store data. 1.0


In [65]:
! pip install nltk

You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [66]:
import nltk.stem
s = nltk.stem.SnowballStemmer('english')

In [67]:
s.stem('graphics')

'graphic'

In [68]:
s.stem("imaging")

'imag'

In [69]:
s.stem("image")

'imag'

In [70]:
s.stem("imagination")

'imagin'

In [71]:
s.stem("imagine")

'imagin'

In [72]:
import nltk.stem
english_stemmer = nltk.stem.SnowballStemmer('english')

class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [73]:
vectorizer = StemmedCountVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())


['actual', 'capabl', 'contain', 'data', 'databas', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'provid', 'safe', 'storag', 'store', 'stuff', 'toy']


In [76]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])
new_post_vec.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [77]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.414213562373095
Imaging databases provide storage capabilities. 0.8573732768944039
Most imaging databases safe images permanently. 0.6296288974669553
Imaging databases store data. 0.7653668647301795
Imaging databases store data. Imaging databases store data. Imaging databases store data. 0.7653668647301795


In [78]:
from sklearn.feature_extraction.text import TfidfVectorizer
class StemmedTfidfVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(TfidfVectorizer,self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))


In [79]:
vectorizer = StemmedTfidfVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())

['actual', 'capabl', 'contain', 'data', 'databas', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'provid', 'safe', 'storag', 'store', 'stuff', 'toy']


In [81]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])
#new_post_vec.toarray()

In [82]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.4142135623730951
Imaging databases provide storage capabilities. 1.0789758507558254
Most imaging databases safe images permanently. 0.859044512133176
Imaging databases store data. 0.924634506718001
Imaging databases store data. Imaging databases store data. Imaging databases store data. 0.924634506718001


## 中文詞頻矩陣

In [86]:
import jieba
jieba.load_userdict('userdict.txt')

a = ['柯文哲為了大巨蛋一事找趙藤雄算帳', 
     '柯P將不在大巨蛋舉辦世運會']

corpus = []
for s in a:
    corpus.append(' '.join(jieba.cut(s)))
corpus


['柯文哲 為 了 大巨蛋 一事 找 趙藤雄 算帳', '柯P 將不在 大巨蛋 舉辦 世運會']

In [87]:
corpus = [' '.join(jieba.cut(s)) for s in a]
corpus

['柯文哲 為 了 大巨蛋 一事 找 趙藤雄 算帳', '柯P 將不在 大巨蛋 舉辦 世運會']

In [92]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [91]:
vectorizer.get_feature_names()

['一事', '世運會', '大巨蛋', '將不在', '柯p', '柯文哲', '算帳', '舉辦', '趙藤雄']

In [93]:
X.toarray()

array([[1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [94]:
import requests
term = '柯文哲'
res = requests.get('https://zh.wikipedia.org/wiki/{}'.format(term))

In [100]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(res.text, 'lxml')
synonyms = []
for p in soup.select('p'):
    if p.select_one('span'):
        synonyms.extend([w.text for w in p.select('b')])
synonyms

['柯文哲', 'Ko Wen-je', '柯P', 'KP']

In [103]:
with open('synonym.txt', 'w') as f:
    f.write('/'.join(synonyms))

In [112]:
synoym_dic = {}
for s in open('synonym.txt', 'r'):
    words = s.split('/')
    for w in words[1:]:
        synoym_dic[w.lower()] = words[0]
synoym_dic

{'ko wen-je': '柯文哲', 'kp': '柯文哲', '柯p': '柯文哲'}

In [113]:
class SynonymCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(SynonymCountVectorizer, self).build_analyzer()
        return lambda doc: (synoym_dic.get(w, w) for w in analyzer(doc))

In [114]:
vectorizer = SynonymCountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['一事', '世運會', '大巨蛋', '將不在', '柯文哲', '算帳', '舉辦', '趙藤雄']


In [115]:
X.toarray()

array([[1, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 0]], dtype=int64)

In [116]:
vectorizer = SynonymCountVectorizer(stop_words=['一事'])
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['世運會', '大巨蛋', '將不在', '柯文哲', '算帳', '舉辦', '趙藤雄']


### 中文停用字詞
- https://github.com/tomlinNTUB/Python-in-5-days/blob/master/10-2%20%E4%B8%AD%E6%96%87%E6%96%B7%E8%A9%9E-%E7%A7%BB%E9%99%A4%E5%81%9C%E7%94%A8%E8%A9%9E.md

In [123]:
import pandas
s = pandas.read_clipboard(header = None)
stopwords = s[0].tolist()

In [125]:
#stopwords

## 計算文章相似度

In [117]:
import pandas
news = pandas.read_excel('https://raw.githubusercontent.com/ywchiu/ctbc/master/data/appledaily_hw.xlsx')

In [121]:

corpus = []
titles = []
for rec in news.iterrows():
    titles.append(rec[1].title)
    corpus.append(' '.join(jieba.cut(rec[1].content)))

In [146]:
import re
class ChineseCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(ChineseCountVectorizer, self).build_analyzer()
        return lambda doc: (w for w in analyzer(doc) if re.match('[\u4e00-\u9fa5]+', w))

In [150]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = ChineseCountVectorizer(stop_words=stopwords)
X = vectorizer.fit_transform(corpus)

In [151]:
X

<899x36095 sparse matrix of type '<class 'numpy.int64'>'
	with 113215 stored elements in Compressed Sparse Row format>

In [128]:
from sklearn.metrics.pairwise import cosine_distances
cs = cosine_distances(X)

In [130]:
cs.shape

(899, 899)

In [132]:
titles[0]

'【更新】水利會改官派明闖關\u3000綠委24小時前顧議場大門防藍突襲'

In [137]:
for idx in cs[0].argsort()[1:11]:
    if cs[0][idx] < 0.8:
        print(titles[idx], cs[0][idx])

反對水利會改制　吳敦義下令：藍委做好夜宿立院抗爭準備 0.6249319023845766
農田水利會改公務機關　蔡英文：這不是綁樁 0.6650818913541277
【搏感情動畫】台電每年30億敦親睦鄰費　協助立委選民服務 0.7763414418773449
在野黨突襲表決《勞基法》修正案無效　民進黨烙人成功擋下 0.7785595271207466
罷免案將投票　李遠哲今再度現身力挺黃國昌 0.7821725817618267
國防部解約慶富要提告　馮世寬怒嗆三遍：請便 0.787735535313332


In [138]:
def getSimiliarArticle(pos):
    print('查詢文章:', titles[pos])
    for idx in cs[pos].argsort()[1:11]:
        if cs[pos][idx] < 0.8:
            print('相關文章:',titles[idx], cs[pos][idx])

In [140]:
getSimiliarArticle(12)

查詢文章: 黃國昌：長期目標要消滅國民黨　不支持柯文哲的兩岸一家親
相關文章: 「兩蔣時代」超譯　網友：不准傷皇城內的和氣！ 0.573991318811758
相關文章: 罷免案將投票　李遠哲今再度現身力挺黃國昌 0.5856440615013038
相關文章: 罷昌案周六投票　時代力量全力澄清不實謠言 0.629022271791837
相關文章: 黃國昌若被罷免會更強　他：成為選輸北市的阿扁 0.6310238769836006
相關文章: 【聲援片】沈發惠呼籲罷昌案投「不同意」　黃國昌：謝謝您 0.7457647744915028


In [162]:
csw = cosine_distances(X.T)

In [163]:
csw.shape

(36095, 36095)

In [170]:
#titles[]

In [168]:
vectorizer.get_feature_names().index('小嫻')

12028

In [169]:
for idx in csw[12028].argsort()[1:11]:
    print(vectorizer.get_feature_names()[idx], csw[12028][idx])

何守 0.057847605573501104
密友 0.24791062532467667
何守正 0.2503553599400147
健身房 0.2884303103522792
信妙 0.3126823393798195
分居 0.34939790478943866
宮導致 0.3514046374402636
何家 0.3578979193561096
獨子 0.36503471393081455
不孕 0.36655934526106637


In [160]:
csw[19153].sort()

## 文字分群

In [171]:
import pandas
news = pandas.read_excel('https://raw.githubusercontent.com/ywchiu/ctbc/master/data/20150628news.xlsx')

In [175]:
corpus = []
titles = []
for rec in news.iterrows():
    corpus.append(' '.join(jieba.cut(rec[1]['description'])))
    titles.append(rec[1]['title'])

In [176]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [177]:
X

<147x12827 sparse matrix of type '<class 'numpy.int64'>'
	with 23782 stored elements in Compressed Sparse Row format>

In [178]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(X)

In [179]:
cs.shape

(147, 147)

In [180]:
from sklearn import cluster
km = cluster.KMeans(n_clusters=4, init='k-means++', random_state=42)
c = km.fit_predict(cs)


In [186]:
np_titles = np.array(titles)
for rec in np_titles[c==3]:
    print(rec)

希臘國內三分一自動櫃員機現金短缺
歐元區財長拒希臘延長救助計劃
呂紹煒專欄：違約與退出 希臘與歐洲才能重生(上)
希臘違約在即  歐盟全力穩定經濟
希臘脫歐變可能 歐洲衝擊大
希債協議  法國願盡最後斡旋努力
希臘1／3提款機錢被提光
確保銀行穩定 希臘續與ECB緊密合作
希臘態度強硬 歐元區耐心漸失
希臘盼展延債務 歐元區拒絕


## 任務：
- 請將資料集 20171214news.xlsx (https://raw.githubusercontent.com/ywchiu/ctbc/master/data/20171214news.xlsx) 分成20群並檢視每一群的分群結果