## 英文詞頻矩陣

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
#?CountVectorizer
vectorizer = CountVectorizer(min_df=1)
content = ["How to format my hard disk", " Hard disk format problems "]
X = vectorizer.fit_transform(content)

In [4]:
print(vectorizer.get_feature_names())

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']


In [5]:
print(X.toarray())

[[1 1 1 1 1 0 1]
 [1 1 1 0 0 1 0]]


In [8]:
import os
path = 'data/toy/'
posts = []
for fname in os.listdir(path):
    posts.append(open(path + fname).read())

In [9]:
posts

['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [16]:
posts = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=1)

In [11]:
X_train = vectorizer.fit_transform(posts)
num_samples, num_features = X_train.shape


In [12]:
X_train.shape

(5, 25)

In [15]:
print(vectorizer.get_feature_names())

['about', 'actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'this', 'toy']


In [13]:
X_train.toarray()

array([[1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0],
       [0, 0, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 0]], dtype=int64)

In [20]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])


In [21]:
new_post_vec.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [40]:
type(new_post_vec.toarray())

numpy.ndarray

In [22]:
import scipy as sp

# euclidean
# sqrt(sum((v1 - v2) ** 2))

def dist_raw(v1, v2):
    delta = v1 - v2
    return sp.linalg.norm(delta.toarray())


In [30]:
import numpy as np
import math
a  = np.array([0,0,1,1,0])
b  = np.array([1,0,1,1,1])
np.sqrt(sum((a - b) ** 2))

1.4142135623730951

In [32]:
sp.linalg.norm( (a - b))

1.4142135623730951

In [45]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist_raw(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 3.872983346207417
Imaging databases provide storage capabilities. 2.0
Most imaging databases safe images permanently. 2.23606797749979
Imaging databases store data. 1.7320508075688772
Imaging databases store data. Imaging databases store data. Imaging databases store data. 5.5677643628300215


In [55]:
def dist(v1, v2):
    v1_normalized  = v1 / sp.linalg.norm(v1.toarray()) 
    v2_normalized  = v2 / sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())


In [46]:
# 小內閣之一是她？ 「王淺秋」內定高市新聞局長
# 韓國瑜要在一個月內完成小內閣組閣，局處首長人選，他說目前找到了一半，至於名單有誰，韓國瑜說直接講名字很敏感，會在就職日公布，不過前一天，韓國瑜北上參加私人餐會，媒體在現場等待時間，六福集團的公關協理王淺秋儼然像公關，在場當協調橋樑，加上王淺秋過去就有新聞媒體背景，外傳將接任高雄市新聞局長。

In [47]:
# 小內閣 王淺秋 高市 新聞局長
# 小內閣 王淺秋 高市 新聞局長 韓國瑜 首長 人選 一半 名單 敏感...

In [51]:
a = np.array([1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
b = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
delta = a - b
sp.linalg.norm(delta)

4.0

In [53]:
a = np.array([1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
b = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
a_normalized  = a / sp.linalg.norm(a) 
b_normalized  = b / sp.linalg.norm(b)
delta = a_normalized - b_normalized
sp.linalg.norm(delta)

1.0514622242382672

In [56]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.4142135623730951
Imaging databases provide storage capabilities. 1.0514622242382672
Most imaging databases safe images permanently. 1.0878894332937856
Imaging databases store data. 1.0
Imaging databases store data. Imaging databases store data. Imaging databases store data. 1.0


In [62]:
vectorizer = CountVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())


['actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'learning', 'machine', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'toy']


In [59]:
len(vectorizer.get_feature_names())

18

In [60]:
list(vectorizer.get_stop_words())[0:10]

['noone',
 'our',
 'next',
 'her',
 'other',
 'formerly',
 'around',
 'fifteen',
 'rather',
 'nevertheless']

In [63]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])


In [64]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.4142135623730951
Imaging databases provide storage capabilities. 1.0514622242382672
Most imaging databases safe images permanently. 1.0514622242382672
Imaging databases store data. 1.0
Imaging databases store data. Imaging databases store data. Imaging databases store data. 1.0


In [65]:
! pip install nltk

You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [66]:
import nltk.stem
s = nltk.stem.SnowballStemmer('english')

In [67]:
s.stem('graphics')

'graphic'

In [68]:
s.stem("imaging")

'imag'

In [69]:
s.stem("image")

'imag'

In [70]:
s.stem("imagination")

'imagin'

In [71]:
s.stem("imagine")

'imagin'

In [72]:
import nltk.stem
english_stemmer = nltk.stem.SnowballStemmer('english')

class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [73]:
vectorizer = StemmedCountVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())


['actual', 'capabl', 'contain', 'data', 'databas', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'provid', 'safe', 'storag', 'store', 'stuff', 'toy']


In [76]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])
new_post_vec.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [77]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.414213562373095
Imaging databases provide storage capabilities. 0.8573732768944039
Most imaging databases safe images permanently. 0.6296288974669553
Imaging databases store data. 0.7653668647301795
Imaging databases store data. Imaging databases store data. Imaging databases store data. 0.7653668647301795


In [78]:
from sklearn.feature_extraction.text import TfidfVectorizer
class StemmedTfidfVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(TfidfVectorizer,self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))


In [79]:
vectorizer = StemmedTfidfVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())

['actual', 'capabl', 'contain', 'data', 'databas', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'provid', 'safe', 'storag', 'store', 'stuff', 'toy']


In [81]:
new_post = 'qoo imaging database'
new_post_vec = vectorizer.transform([new_post])
#new_post_vec.toarray()

In [82]:
for i in range(0, num_samples):
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print(posts[i],d)

This is a toy post about machine learning. Actually, it contains not much interesting stuff. 1.4142135623730951
Imaging databases provide storage capabilities. 1.0789758507558254
Most imaging databases safe images permanently. 0.859044512133176
Imaging databases store data. 0.924634506718001
Imaging databases store data. Imaging databases store data. Imaging databases store data. 0.924634506718001


## 中文詞頻矩陣

In [86]:
import jieba
jieba.load_userdict('userdict.txt')

a = ['柯文哲為了大巨蛋一事找趙藤雄算帳', 
     '柯P將不在大巨蛋舉辦世運會']

corpus = []
for s in a:
    corpus.append(' '.join(jieba.cut(s)))
corpus


['柯文哲 為 了 大巨蛋 一事 找 趙藤雄 算帳', '柯P 將不在 大巨蛋 舉辦 世運會']

In [87]:
corpus = [' '.join(jieba.cut(s)) for s in a]
corpus

['柯文哲 為 了 大巨蛋 一事 找 趙藤雄 算帳', '柯P 將不在 大巨蛋 舉辦 世運會']

In [92]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [91]:
vectorizer.get_feature_names()

['一事', '世運會', '大巨蛋', '將不在', '柯p', '柯文哲', '算帳', '舉辦', '趙藤雄']

In [93]:
X.toarray()

array([[1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [94]:
import requests
term = '柯文哲'
res = requests.get('https://zh.wikipedia.org/wiki/{}'.format(term))

In [100]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(res.text, 'lxml')
synonyms = []
for p in soup.select('p'):
    if p.select_one('span'):
        synonyms.extend([w.text for w in p.select('b')])
synonyms

['柯文哲', 'Ko Wen-je', '柯P', 'KP']

In [103]:
with open('synonym.txt', 'w') as f:
    f.write('/'.join(synonyms))

In [112]:
synoym_dic = {}
for s in open('synonym.txt', 'r'):
    words = s.split('/')
    for w in words[1:]:
        synoym_dic[w.lower()] = words[0]
synoym_dic

{'ko wen-je': '柯文哲', 'kp': '柯文哲', '柯p': '柯文哲'}

In [113]:
class SynonymCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(SynonymCountVectorizer, self).build_analyzer()
        return lambda doc: (synoym_dic.get(w, w) for w in analyzer(doc))

In [114]:
vectorizer = SynonymCountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['一事', '世運會', '大巨蛋', '將不在', '柯文哲', '算帳', '舉辦', '趙藤雄']


In [115]:
X.toarray()

array([[1, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 0]], dtype=int64)

In [116]:
vectorizer = SynonymCountVectorizer(stop_words=['一事'])
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['世運會', '大巨蛋', '將不在', '柯文哲', '算帳', '舉辦', '趙藤雄']
