In [3]:
qa = {
 '早安': '你也早安',
 '掰掰': '期待下次再會',
 '晚安': '你也晚安'   
}

question = input('請問你要問什麼問題?')
qa.get(question, '我現在還不聰明，以後變聰明以後，再回答你')

請問你要問什麼問題?幾歲


'我現在還不聰明，以後變聰明以後，再回答你'

In [4]:
import requests
res = requests.get('https://www.ctbcbank.com/CTCBPortalWeb/toPage?id=TW_RB_CM_service_000007')

In [6]:
#res.text

In [12]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(res.text, 'lxml')
#for q in soup.select('.eventgoldtitle02 strong'):
questions = []
for q in soup.select('.style01-1'):
    questions.append(q.text)
#questions

In [13]:
answers = []
for a in soup.select('#QAContent p'):
    answers.append(a.text)

In [14]:
questions = [q.text for q in soup.select('.style01-1')]
answers   = [a.text for a in soup.select('#QAContent p')]

In [16]:
zip(questions, answers)

In [18]:
#for rec in zip(questions, answers):
#    print(rec)

In [21]:
import pandas
ctbc_qa = pandas.DataFrame(list(zip(questions, answers)), columns = ['question', 'answer'])

In [23]:
#ctbc_qa

In [26]:
import jieba
for w in jieba.cut('毀補後多久可補發新卡? 會不會另要收費？'):
    print(w)

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/46/b7dzk4mn6g54qzptv608w7d00000gn/T/jieba.cache
Loading model cost 0.924 seconds.
Prefix dict has been built succesfully.


毀補
後
多久
可補
發新卡
?
 
會不會
另
要
收費
？


In [27]:
list(jieba.cut('毀補後多久可補發新卡? 會不會另要收費？'))

['毀補', '後', '多久', '可補', '發新卡', '?', ' ', '會不會', '另', '要', '收費', '？']

In [28]:
jieba.load_userdict('userdict.txt')

In [29]:
list(jieba.cut('毀補後多久可補發新卡? 會不會另要收費？'))

['毀補', '後', '多久', '可', '補發', '新卡', '?', ' ', '會不會', '另', '要', '收費', '？']

In [30]:
sentence='那我們酸民婉君也可以報名嗎'
len(sentence)

13

In [32]:
#for i in range(0,13 - 2 + 1 ):
for i in range(0,len(sentence) - 2 + 1 ):
    print(sentence[i:i+2])

那我
我們
們酸
酸民
民婉
婉君
君也
也可
可以
以報
報名
名嗎


In [33]:
for i in range(0,len(sentence) - 3 + 1 ):
    print(sentence[i:i+3])

那我們
我們酸
們酸民
酸民婉
民婉君
婉君也
君也可
也可以
可以報
以報名
報名嗎


In [34]:
def ngram(input_sentence,n=2):
    ret = []
    for i in range(0,len(input_sentence) - n + 1):
        ret.append(input_sentence[i:i+n])
    return ret


In [35]:
a = '''
全球080就是國際性080免付費服務電話。相同於080-024-365為免付費服務電話，您可透過此080電話從國外地區直接與我們聯絡，並由本行承擔所有的通話費用，稍有差別的是080-024-365僅限於台灣地區使用，而全球 080則於國外地區使用。
您可於當地直接撥當地之免費撥接號碼，不進入語音系統，不需輸入任何卡號或密碼。
註：手機無法撥打全球080，請儘量使用當地室內電話撥打全球080專線。
'''

In [38]:
from collections import Counter
c = Counter(ngram(a,2))
#c.most_common()

In [40]:
from collections import Counter
c = Counter(ngram(a,3))
#c.most_common()

In [47]:
import re
delimiter = "，|。"  
text = '''全球080就是國際性080免付費服務電話。相同於080-024-365為免付費服務電話，您可透過此080電話從國外地區直接與我們聯絡，並由本行承擔所有的通話費用，稍有差別的是080-024-365僅限於台灣地區使用，而全球 080則於國外地區使用。'''
sentenceAry = []
for i in re.split(delimiter, text):
    sentenceAry.append(i)


In [45]:
def removeKey(text, keywords):
    ret = text
    for word in keywords:
        ret = ret.replace(word, '')
    return ret


In [46]:
a = '比特幣期貨 美核准上市'
removeKey(a, ['期貨', '核准'])


'比特幣 美上市'

In [49]:
keywords = [] 
for n in range(4,1, -1):
    words = []
    for sentence in sentenceAry:
        text_list = removeKey(sentence, keywords)
        words.extend(ngram(text_list, n))
        
    c = Counter(words)
    for word, cnt in c.items():
        if cnt >= 3:
            keywords.append(word)


In [50]:
keywords

['080', '電話', '地區']

In [56]:
res = []
#ctbc_qa['question'].tolist()
res.extend(ctbc_qa['question'].tolist() )
res.extend(ctbc_qa['answer'].tolist() )

In [59]:
text = ' '.join(res)

In [80]:
import re
delimiter = "，|。|\?|\？| |\(|\)|「|」|/|【|】|：|╱"  
sentenceAry = []
for i in re.split(delimiter, text):
    if len(i)>0:
        sentenceAry.append(i)


In [93]:
keywords = [] 
for n in range(9,1, -1):
    words = []
    for sentence in sentenceAry:
        text_list = removeKey(sentence, keywords)
        words.extend(ngram(text_list, n))
        
    c = Counter(words)
    for word, cnt in c.items():
        if cnt >= 30:
            keywords.append(word)


In [96]:
with open('userdict.txt', 'a') as f:
    for w in keywords:
        m = re.match('^[\u4e00-\u9fa5]+$', w)
        if m:
            f.write(w+'\n')

In [120]:
import jieba
jieba.load_userdict('userdict.txt')

a = ['柯文哲為了大巨蛋一事找趙藤雄算帳', '柯P將不在大巨蛋舉辦世運會']

corpus = [' '.join(jieba.cut(s)) for s in a]
corpus


['柯文哲 為 了 大巨蛋 一事 找 趙藤雄 算帳', '柯P 將不在 大巨蛋 舉辦 世運會']

In [121]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)


In [122]:
vectorizer.get_feature_names()

['一事', '世運會', '大巨蛋', '將不在', '柯p', '柯文哲', '算帳', '舉辦', '趙藤雄']

In [123]:
X

<2x9 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [124]:
corpus = []
for q in ctbc_qa['question'].tolist():
    corpus.append(' '.join(jieba.cut(q)))

In [125]:
corpus = [' '.join(jieba.cut(q)) for q in ctbc_qa['question'].tolist()]

In [126]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [136]:
#print(vectorizer.get_feature_names())

In [134]:
synonym_dic = {}
with open('synonym.txt', 'r') as f:
    for line in f:
        fields = line.strip().split('/')
        for field in fields[1:]:
            synonym_dic[field] = fields[0]

In [172]:
class SynonymCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(SynonymCountVectorizer, self).build_analyzer()
        return lambda doc: (synonym_dic.get(w, w) for w in analyzer(doc))

In [173]:
vectorizer = SynonymCountVectorizer()
X = vectorizer.fit_transform(corpus)
#print(vectorizer.get_feature_names())

## Distance Calculation

In [145]:
import numpy as np
import math
a = np.array([1,0,1,1,1])
b = np.array([1,1,1,0,1])
math.sqrt(sum((a - b) ** 2))

1.4142135623730951

In [147]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances([a,b])

array([[0.        , 1.41421356],
       [1.41421356, 0.        ]])

In [149]:
title   = '銀行業去年平均年薪　兆豐223萬奪冠'
content = '立委曾銘宗在今天財委會上，出具一份數據，去年全體銀行員工平均薪資中，以兆豐銀平均每位員工薪資達223.4萬元居冠，打敗中信銀的203.6萬元，而全體平均37家銀行員工平均薪資是142.9萬元，但最後一名銀行的平均員工薪資是82.8萬元，和最高的兆豐銀、高低差距了2.69倍，也與平均薪資差了1.72倍' 

corpus2 = [' '.join(jieba.cut(title)), ' '.join(jieba.cut(content))]
vectorizer2 = CountVectorizer()
X2 = vectorizer2.fit_transform(corpus2)

In [152]:
euclidean_distances(X2)

array([[0.        , 9.38083152],
       [9.38083152, 0.        ]])

In [170]:
a = np.array([1,0,1,1,1])
b = np.array([1,1,1,0,1])
(a * b).sum() / (math.sqrt((a ** 2).sum()) * math.sqrt((b ** 2).sum()) )

0.75

In [171]:
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity
cosine_similarity([a,b])

array([[1.  , 0.75],
       [0.75, 1.  ]])

In [166]:
cosine_distances([a,b])

array([[0.  , 0.25],
       [0.25, 0.  ]])

In [174]:
cs = cosine_distances(X)

In [175]:
cs.shape

(324, 324)

In [230]:
user_input = input('請輸入你的問題：')

請輸入你的問題：我想要開戶，請問我該準備哪些文件


In [231]:
c = [' '.join(jieba.cut(user_input))]

In [232]:
user_vec = vectorizer.transform(c)

In [233]:
user_vec

<1x724 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [234]:
cs = cosine_distances(user_vec,X)

In [235]:
cs.shape

(1, 324)

In [236]:
cs.argsort()[0][0]

140

In [237]:
ctbc_qa.iloc[cs.argsort()[0][0]]

question                                           開戶應攜帶什麼文件?
answer      只要您持有本行信用卡正卡，且您的車輛已有申請eTag服務，就可以申請信用卡代扣繳eTag自動...
Name: 140, dtype: object